### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by Error996** [benjojo/bondcat#2]
i only success wih:
> server:
`bondcat -l -p 9090`
> client:
`bondcat -b  x.x.x.x:9090`

result:
```
RX: 0 B (0 B/s)         TX: 0 B (0 B/s)
RX: 0 B (0 B/s)         TX: 864.0 KiB (864.0 KiB/s)
RX: 0 B (0 B/s)         TX: 1.6 MiB (800.0 KiB/s)
RX: 0 B (0 B/s)         TX: 2.9 MiB (1.2 MiB/s)
RX: 0 B (0 B/s)         TX: 4.6 MiB (1.7 MiB/s)
RX: 0 B (0 B/s)         TX: 6.7 MiB (2.1 MiB/s)
RX: 0 B (0 B/s)         TX: 9.9 MiB (3.2 MiB/s)
RX: 0 B (0 B/s)         TX: 13.8 MiB (3.9 MiB/s)
RX: 0 B (0 B/s)         TX: 19.4 MiB (5.6 MiB/s)
RX: 0 B (0 B/s)         TX: 26.5 MiB (7.0 MiB/s)
```

**Comment by benjojo** [comment]
This critically depends on your connectivity situation, Can you describe how the server and client are connected?

**Comment by Error996** [comment]
Client(with PPPOE)<------->Internat<------->Server

**Comment by benjojo** [comment]
Assuming you have just one link between your client and server, bondcat will not be useful to you

**Comment by Error996** [comment]
i have two pppoe

**Comment by benjojo** [comment]
Ok, so a lot of this depends on how your two links are setup, and there are two easy ways to ensure bondcat can easily work without any annoying magic.

If the Server side has two IP addresses, and you can direct each IP to go over each modem, you can just do:

Server (who has both  A.A.A.A B.B.B.B)
```
bondcat -l -p 9090
```

Client (whos router forces A.A.A.A to go down one modem, and B.B.B.B to the other)
```
bondcat -no-auto-detect A.A.A.A:9090 B.B.B.B:9090
```

---

The other solution is to do it in reverse, and port forward on both modems and have the server connect IN:

Server
```
bondcat C.C.C.C:9090 D.D.D.D:9090
```

Client (who has port forwarding setup on both modems to go to the client)
```
bondcat -l -p 9090
```

---

Does this help?

**Comment by Error996** [comment]
Got it
if i run in my router(linux),how dose lan pc to use this link

**Comment by benjojo** [comment]
If the system you are running it on itself has both links, you MIGHT be able to get away with just:

Server:
```
bondcat -l -p 9090
```

Client:
```
bondcat E.E.E.E:9090 
```

and bondcat might be able to auto detect the setup and automatically start two different connections.

But that depends a lot on how the router is setup, "Linux with PPPoE" covers in a near infinite amount of different setups.

**Comment by Error996** [comment]
my router: vyos 1.4
and i set two pppoe,get two ip, A.A.A.A and B.B.B.B,LAN ip 192.168.0.1
my server ip C.C.C.C
lan pc under router(vyos) ip 192.168.0.3
if bondcat build two connectios with router and server,how does lan pc enjoy this?
or just two connetions?

**Comment by Error996** [comment]
For example
Router:
`bondcat -l -p 9090`
Server:
`bondcat A.A.A.A:9090 B.B.B.B:9090`
Original if i want ssh server ,i need:
`ssh root@C.C.C.C`
What about now?

**Comment by benjojo** [comment]
I'm not sure bondcat can immediately help you.

I also don't want to support your router setup.

---

To use bondcat you need two distinct paths available to you, this can either be though:

 * Hashing (or "load balancing" as it is called in some configurations)
   * Then you will find that `-multiplier 2` should bring some benefit. 
 * Distinct IP addressing
   * This is the setup I was describing above, In your situation you will need your router to force both IP addresses down different modems (PPPoE) for this to work correctly.

This use-case you are trying to do is tricky without additional network/router configuration , and is not really what bondcat had in mind for usage.
